### ISSUE TITLE
Extract has_any_present_attributes?

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#100]
Let's pull this out of the helper, push it into the model layer, and test.

**Comment by nathanstruhs** [comment]
Hi @ybakos, Im curious to your reason for extracting this method, and which model it belongs to? 

If we extract to it each of our 6 different sample model, we would be defining the method 6 times. 

On the other side if we extract to the BD model, wouldn't you have to the call the method on a BD object? (When the method only deals with the sample objects)

**Comment by ybakos** [comment]
In typed languages, we'd do something like:

```
interface AttributeStateReporter {
    bool hasAnyPresentAttributes();
}

class SoilSample implements AttributeStateReporter {
    // ...
    bool hasAnyPresentAttributes() {
        !attr1.blank? || !attr2.blank?;
    }
}
```

In our case, we would just implement `has_any_present_attributes?` in each of the *Sample classes.

Another approach is to define the method in `ApplicationRecord`, so each *Sample class would inherit something like

```
def has_any_present_attributes?
    attributes.each { |name, value| return true if name != "biodiversity_report_id" && value.present? }
    return false
end
```

but this also has its drawbacks.

The ideal might be figuring out how to enable us to do something like:

```
class SoilSample < ApplicationRecord
    communicate_present_attributes :excluding => 'biodiversity_report_id'
end

class FungiSample < ApplicationRecord
    communicate_present_attributes :excluding => 'biodiversity_report_id'
end
```

That last one would be a great Ruby exercise.

**Comment by nathanstruhs** [comment]
@ybakos I went with the ApplicationRecord implementation but, I do like your last recommendation a lot. I agree it would be a great exercise, but I think I need a bit more guidance. I feel like once I knew how to ask the question, I would know the answer. hah (but heres my attempt)

- Are methods like `communicate_present_attributes` called something particular? (Similar to `belongs_to`, or 'validates')
- Are they generally defined in ApplicationRecord as well?
- When they are written in the class, is the argument redefining/altering the method?

**Comment by ybakos** [comment]
@nathanstruhs You're asking all the right questions. We casually call these things, like `has_many` and the AR validators, "macros." I think a good place to start is here: https://pragmaticstudio.com/blog/2015/4/14/ruby-macros

**Comment by nathanstruhs** [comment]
@ybakos Wow, that was a good tut. Really expanded my view of how Rails/Ruby works. 👍🏼
