### ISSUE TITLE
Elm temperature slider only displays after a browser refresh

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/ecotone-web#104]
Branch: development

**Comment by ybakos** [comment]
sounds like a turbolinks issue...

**Comment by ybakos** [comment]
sounds like a turbolinks issue...

**Comment by nathanstruhs** [comment]
Hi @ybakos, hoping you could help me out with this one.  I tried to update the javascript to use 'turbolinks:load' ([02d80c4](https://github.com/osu-cascades/ecotone-web/commit/02d80c474b5d0141456598887d70448225dcadf7)), but that has no effect.

**Comment by ybakos** [comment]
References #103

**Comment by ybakos** [comment]
See https://github.com/fbonetti/elm-rails/issues/23

**Comment by ybakos** [comment]
https://www.reddit.com/r/elm/comments/6wtx1h/really_integrating_elm_with_rails_5_webpacker_and/
