### ISSUE TITLE
Gemfile: Bump bootstrap-sass version

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#148]
https://github.com/osu-cascades/ecotone-web/network/alert/Gemfile.lock/bootstrap-sass/open

**Comment by FrancescoAiello01** [comment]
It looks like ruby-sass, a dependency of sass-rails has reached the end of its life and it is recommended to be migrated to sassc-rails:

[https://sass-lang.com/ruby-sass](https://sass-lang.com/ruby-sass)

sass-rails version 6.0.0 is a breaking change that moves to sassc-rails ([https://github.com/rails/sass-rails/releases](https://github.com/rails/sass-rails/releases)). 

Do we want to upgrade to sassc-rails in this PR or handle it elsewhere?

**Comment by ybakos** [comment]
@FrancescoAiello01 True, but we'll need to address that separately, as a complete migration away from bootstrap-sass to the bootstrap gem. The bootstrap-sass gem uses bootstrap 3 CSS selectors, while the bootstrap gem uses bootstrap 4.

To swap those in, we'd likely need to make numerous changes throughout the views and app stylesheet.

For now, just bump the `bootstrap-sass` version to resolve the security issue.
