### ISSUE TITLE
Upgrade puma to 3.12.6

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#151]

**Comment by FrancescoAiello01** [comment]
@ybakos Are we wanting to upgrade specifically to version 3.12.6 or do we want the newest version 4.2.1?

**Comment by ybakos** [comment]
Try upgrading to 3.12.6 first, make sure it runs ok. Then, try upgrading to the latest.

**Comment by ybakos** [comment]
@FrancescoAiello01 Latest is 4.3.5. See:

https://rubygems.org/gems/puma

I merged the original PR w/o properly verifying the latest version. Can you please submit a new PR with the bump to 4.3.5? Thank you!

**Comment by FrancescoAiello01** [comment]
@ybakos Just got that email too. Sorry about that!! I'll submit the PR now.
