### ISSUE TITLE
spec/rails_helper.rb: Simplify webpack build

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#158]
We needed to add a short-term hack for rspec, Rails 5.1.7 and webpacker in https://github.com/osu-cascades/ecotone-web/pull/157 .

Once Rails and rspec are updated to the latest versions, see about removing the hack.

Notes:
Changing the travis build config?

**Comment by NikitaRubocki** [comment]
Webpack build does not exist anymore, this issue can be closed
