### ISSUE TITLE
plants/new: Make list resulting view after add

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#16]
Let's return the user to the list.
Would be nice to highlight the row of the recently added plant, with a little fade effect.

**Comment by nathanstruhs** [comment]
@ybakos can you point me in the right direction on how to highlight the last added? I thought about giving that specific <li> a class, but we dont want it to persist past the first page view..

**Comment by ybakos** [comment]
Yep, no prob re: helping w/ the highlighting of the most recent element. Let's deprioritize that for now. Go ahead and close this (for the glory) and I'll open another issue to track the highlighting feature.
