### ISSUE TITLE
Fix Travis CI recaptcha errors

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/ecotone-web#17]
From what I have read online it looks like a test environment should ignore captchas, not sure where to go from here

**Comment by ybakos** [comment]
Ok, I'll tinker with this. Yes, recaptcha should automatically be ignored in the 'test' env. It's possible Travis is running in a different env and that we have to explicitly configure the rails env before it runs the test suite. (?)

**Comment by ybakos** [comment]
@nathanstruhs This is now fixed. Just needed to add a SITE_KEY env var to the travis config.

[![Build Status](https://travis-ci.org/osu-cascades/ecotone-web.svg?branch=master)](https://travis-ci.org/osu-cascades/ecotone-web)
