### ISSUE TITLE
Adding Additional Contribution Documentation

### ISSUE THREAD

**Issue by LexiSchindel** [osu-cascades/ecotone-web#177]
For new contributors interested in helping with this app, there is minimal documentation related to contribution guidelines and said documentation isn't linked in the README.

I would love to help begin crafting some of this with you to help outline what you expect of/from contributors and hopefully attract more contributors to this project. Is this something I can help with? 

I'm a current student at OSU in the Open Source class.

**Comment by ybakos** [comment]
Sure @LexiSchindel !

Please fork and send pull requests.

See CONTRIBUTING and the README for details, and feel free to start by improving there.

Closing this issue in lieu of specific documentation / other changes / bugs that can be resolved w/ commits.

**Comment by LexiSchindel** [comment]
Great, will do. Looking forward to adding to that documentation!
