### ISSUE TITLE
Plot create fails in staging

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/ecotone-web#28]
Heroku log error: Paperclip::Error (Plot model missing required attr_accessor for 'photo_file_name'):

**Comment by ybakos** [comment]
Let me know if you get stuck on this and I'll troubleshoot.
Model and migrations look fine...

**Comment by nathanstruhs** [comment]
@ybakos that would be great. thanks Yong

**Comment by ybakos** [comment]
It's working. I did nothing but retry. I think perhaps that the Heroku dyno was live and running the app, then the migration was run, but the model hadn't reloaded and needed a restart of the application. Now that the app has spun down and up again (restarting the app) it works as expected.

Give it a shot and let me know if you still encounter the error.
