### ISSUE TITLE
Integrate google authentication

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#29]

**Comment by ybakos** [comment]
Let's move away from the hand-rolled authentication implementation and use Devise with OmniAuth and the oauth plugin for the google integration.

https://www.sitepoint.com/authenticating-google/

Testing tips:

"automated testing" section: https://www.interexchange.org/articles/engineering/lets-devise-google-oauth-login/

http://www.jessespevack.com/blog/2016/10/16/how-to-test-drive-omniauth-google-oauth2-for-your-rails-app

**Comment by ybakos** [comment]
@bennetthanna Here's a new one for you. I'll chat w/ you about this. For now, clone and get ecotone-web up and running in dev.

**Comment by bennetthanna** [comment]
0c1058bf3a36733c8dbd22ca7593afe54787bd70...7d1a0a26dfab5cbea13f1afbb1c9f68cc69f3624
