### ISSUE TITLE
Build BiodiversityReport model

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/ecotone-web#38]
- A plot belongs to sample data
- species richness (# of unique species in plot), ability to add existing plants 
- species abundance - # of each species
-  evenness - proportion of diversity of plants (will use function)
- soil collection -> BOOL
- temperature
- date
- time
- optional photos
- biomass estimate
- precent cover (use slider in form?)

**Comment by ybakos** [comment]
@nathanstruhs Changing the name to `BiodiversityReport`.

We'll need two additional models: `PlantSample` and `SoilSample`.

BiodiversityReport: `has_many :plant_samples; has_one :soil_sample; belongs_to :plot; belongs_to :user`
PlantSample: `belongs_to :plant; belongs_to :biodiversity_report`
Plant: `has_many :plant_samples`
SoilSample: `belongs_to :biodiversity_report`

I think...
![image](https://cloud.githubusercontent.com/assets/5502/26788776/29cf7d20-49c3-11e7-9c0c-b66bf2526148.png)

**Comment by ybakos** [comment]
The model layer is pretty sound, and fairly tested, so I'm closing this.
