### ISSUE TITLE
Add optional citation field to plants forms

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/ecotone-web#39]

**Comment by nathanstruhs** [comment]
@ybakos Sarah and Kelly were questioning what the best approach for citing the sources they use for a plant's description. Would it be best to cite the sources directly on the the plant's show screen? Or is there a better way to handle this?

**Comment by ybakos** [comment]
Let's go ahead and add a citation field, and render the contents under the description in `#show`.
