### ISSUE TITLE
Add qrcode property to plots, upon creation

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#45]
https://github.com/whomwah/rqrcode

**Comment by nathanstruhs** [comment]
plants.each create qr code in migration

**Comment by nathanstruhs** [comment]
Hi @ybakos, 

Before I pull the trigger on this migration, I was hoping you could take a look at it: https://github.com/osu-cascades/ecotone-web/blob/qr-code/db/migrate/20170526185353_add_attachment_qr_code_to_plots.rb

Couple questions 
- Should we store the qr codes as svg with paperclip?
- In the migration I am adding a qr code to all existing plots, does it look correct? Specifically, ```QRCode.new()``` takes the url you want the code to take you to as a parameter, will ```qrcode = RQRCode::QRCode.new(plot_path(:id))``` give us the correct url?

**Comment by ybakos** [comment]
Will try to get to this today, 6/26.

**Comment by ybakos** [comment]
@nathanstruhs I think we should avoid storing the generated qrcode image entirely - but correct me if I'm forgetting something. Now that I've had time to take a look at the library, it seems we can just `QRCode.new(plot_path(@plot))` in the view for `plots#show`, embedding the resulting svg/html in the page with the respectful methods.

Bio users can then just print the page and make a little physical qrcode label (we'll have to experiment with this, for sizing, etc) and ultimately we can have a simple "print qr code" button that makes it a little better.

I think using `plot_path` is a smarter approach than `plot_url`, since, although the former requires a little string concatenation with a literal hostname, the latter decouples the qrcode from the hostname (in case it changes later).
