### ISSUE TITLE
Sample Data Branch: undefined method `klass' for nil:NilClass

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/ecotone-web#47]
Hi @ybakos, 

I am hitting a roadblock trying to figure out the dynamic fields_for method. I am attempting to follow this [railscast](http://railscasts.com/episodes/197-nested-model-form-part-2?autoplay=true). From what I have gathered from google, it might be how the relationships are set up? But I believe mine are set up correctly (b/t plots, plants, and sample data)

Link to the relevant [commit](https://github.com/osu-cascades/ecotone-web/commit/b2113b4f95a7532d4455062129bb95cfe971917c)

**Comment by ybakos** [comment]
I'll take a look on Saturday (I think).

**Comment by ybakos** [comment]
@nathanstruhs Let's drop this branch and start over. See #38
