### ISSUE TITLE
BiodiversityReport: form not always working?

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#60]
per Discord chat 6/19/17.

**Comment by ybakos** [comment]
@nathanstruhs So.... it works ok now? In addition to feature specs, I assume you manually tested? (I haven't yet.)

**Comment by nathanstruhs** [comment]
Yup! I manually tested it as well

**Comment by ybakos** [comment]
🎉

**Comment by nathanstruhs** [comment]
@ybakos I was a little unsure as to how far I should take the feature tests, the tests are not covering every permutation that a report could take. I believe that we covering the majority of functionality, but if you think we could use more please let me know!
