### ISSUE TITLE
Test link_to_add_fields

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#73]
I've put a `skip` stub in there with some comments for now.

This is a good testing challenge. I think there are three things to test:

- that an `a` tag is generated
- the value of the `data-id` attribute is what we expect
- the value of the `data-fields` attribute is what we expect

The challenge is deciding how to test, including some `before` work, mocking/stubbing, and perhaps even breaking the `link_to_add_fields` method apart to make it easier to test.

Perhaps a great question to ask on SO.

**Comment by nathanstruhs** [comment]
- [ ] Extract FormBuilder into helper: https://coderwall.com/p/-biuug/custom-form-builders-in-rails
- [ ] Create template: https://content.pivotal.io/blog/testing-custom-form-builders-in-rails
- [ ] Instantiate new CustomFormBuilder and create template, then can test: https://stackoverflow.com/questions/19628063/testing-a-rails-formbuilder-extension

**Comment by jackpetersen3** [comment]
This issue can be closed. It is for testing deprecated biodiversity report features.
