### ISSUE TITLE
Feature: Macroinvertebrates

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/ecotone-web#81]
Students will log none, one, or many macroinvertebrates.

- phylum: STRING
- location: STRING
- quantity: INTEGER
- ecosystem service: STRING, dropdown -> pollinator, consumer or decomposer

**Comment by ybakos** [comment]
Whoah.

**Comment by nathanstruhs** [comment]
- [ ] Clarify with Sarah the naming conventions for total amount of macroinvertebrates present in the plot
