### ISSUE TITLE
Feature: Birds

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/ecotone-web#83]
Admins will log bird species similar to plants within Ecotone. As of right now, birds will not be included in the BD report.

Attributes: 
- common name
- scientific name
- description
- habitat
- bird song (audio clip)
- photo

**Comment by ybakos** [comment]
@nathanstruhs This may be out of scope for Ecotone, I will dig into it and find out.

Per Sarah's recent message in Basecamp, we've just turned a corner: once you show a little bit of success with working software in an organization, suddenly everyone wants to use it and/or add features and/or have another application. (This is a good thing that I have been hoping for here at OSU Cascades.)

Thanks for your ongoing work!

**Comment by nathanstruhs** [comment]
Absolutely! It is exciting that people are interested in using the software.

**Comment by ybakos** [comment]
Out of scope for Ecotone, since the clients' bird interest is not on the Cascades campus.

**Comment by ybakos** [comment]
@nathanstruhs This could become a small webapp of its own in the future.
