### ISSUE TITLE
BiodiversityReport: Clarify destruction of associated models

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#91]
@nathanstruhs I've noticed the recent `after_destroy :destroy_plant_samples` callback. Was this in response to a client-generated feature request? My question is, should we be deleting soil and fungi samples too?

My gut tells me, "yes," but I also think that the concept of a "biodiversity report" seems to have lost its significance... in that users seem to need to "just" enter soil, fungi, and plant samples independently. I may be wrong, but it's worth thinking about and discussing. The benefit is a simpler data model, and especially interface, when users are creating soil/plant/fungi samples.

**Comment by ybakos** [comment]
(That last part is really a separate issue.)

**Comment by nathanstruhs** [comment]
@ybakos the current implementation with the callback ensures that all rows in the plant samples table are fully complete. Without destroying the plant samples, certain columns will remain leaving an incomplete row. 

I agree that the biodiversity report has lost it's significance and with each additional feature the BD report becomes more convoluted in essence and usability. Do you think this would be a question to pose to Sarah or Ann?

**Comment by ybakos** [comment]
@nathanstruhs We should also be destroying fungi and soil samples as well when a bd report is destroyed. Let me know if there's a reason we shouldn't.

**Comment by ybakos** [comment]
@nathanstruhs I spoke w/ Sarah about the concept of the BD Report. It actually makes sense to keep things as they are. While some labs will only incorporate some types of samples, there are cases where the entire BD report (soil, fungi, lichen, moss, bugs, plants) will be complete.

I'm going to close this and create a separate issue regarding destroying associated models.
