### ISSUE TITLE
PlantSample.to_csv: test

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/ecotone-web#92]
See *plant_sample_spec.rb* `it 'generates a valid csv representation'`.

**Comment by nathanstruhs** [comment]
@ybakos This solution doesn't seem to be the most elegant, but I am not sure where else I could go with it. If you have some time could you take a look at it (no rush). Thanks!

**Comment by ybakos** [comment]
@nathanstruhs I think the test is fine - it's clear what it does and what it tests. Would be nice to avoid the creates and use a build with fake ids, and avoid the file i/o, but I wouldn't worry about that now.

We can avoid the database hits by mocking `all` to return an array of the two PlantSample objects, created with `build` instead of `create`.

The file i/o workaround could be a fat multi-line string, eg

```
expected_csv = """
fe, fi, fo
1, 2, 3
"""
```
